#!/bin/sh

i3-msg 'workspace 3; move workspace to output HDMI-A-0'
i3-msg 'workspace 4; move workspace to output HDMI-A-0'
i3-msg 'workspace 5; move workspace to output HDMI-A-0'
i3-msg 'workspace 6; move workspace to output HDMI-A-0'
i3-msg 'workspace 7; move workspace to output HDMI-A-0'
i3-msg 'workspace 8; move workspace to output HDMI-A-0'
i3-msg 'workspace 9; move workspace to output HDMI-A-0'
i3-msg 'workspace 0; move workspace to output HDMI-A-0'
