export PATH=”/home/gartaud/Documents/neovim/bin:$PATH”
export PYTHON_HOST_PROG='/usr/sbin/python'
export PYTHON3_HOST_PROG='/usr/sbin/python3'
export ZSH="$HOME/.oh-my-zsh"
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

ZSH_THEME="robbyrussell"

plugins=(
	git
)

alias vim="nvim"
alias vi="nvim"
alias lzd="lazydocker"
alias msbr="mvn spring-boot:run"
alias msbrd="mvn spring-boot:run -Dspring-boot.run.jvmArguments=\"-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005\""
alias mci="mvn clean install"
alias mcis="mvn clean install -DskipTests"
alias mt="mvn test"
alias mtd="mvn -Dmaven.surefire.debug test"
alias gdh="git diff HEAD"
alias dcu="docker-compose up"
alias dcud="docker-compose up -d"
alias ix="curl -F 'f:1=<-' ix.io"
alias lg="lazygit"
alias zshconfig="vim ~/.zshrc"
alias nvimconfig="nvim ~/.config/nvim/"
alias gcob="git checkout -b"

# enable control-s and control-q
stty start undef
stty stop undef
setopt noflowcontrol

source $ZSH/oh-my-zsh.sh

if service docker status 2>&1 | grep -q "is not running"; then
    wsl.exe -d "${WSL_DISTRO_NAME}" -u root -e /usr/sbin/service docker start >/dev/null 2>&1
fi



export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# pnpm
export PNPM_HOME="/home/gregory/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
